server.port=80
logging.level.root=DEBUG
logging.file.name=watchlist-app.log
spring.profiles.active=production

info.app.name=Watchlist
info.app.description=A must have for any movie buff!
info.app.version=1.0.0